language: python

python:
  - "2.7"
  - "3.6"
install:
  - pip install -e .
  - pip install -r requirements.txt
script:
  - python tests/test_PVDER_LVRT.py
  - python tests/test_PVDER_HVRT.py
  - python tests/test_PVDER_DynamicSimulation.py
  - python tests/test_PVDER_ThreePhase.py
  - python tests/test_PVDER_SinglePhase.py